### ISSUE TITLE
Could not get master role for DRM.

### ISSUE THREAD

**Issue by MirS0bhan** [embear-engineering/drm-framebuffer#10]
hello 
`$ dd if=/dev/urandom | ./drm-framebuffer -d  /dev/dri/by-path/pci-0000:00:02.0-card -c HDMI-A-2 -v
`
i try to run this but i got this error Could not get master role for DRM. what should i do ?

**Comment by eichenberger** [comment]
Hi @MirS0bhan 
Could it be that you have a compositor running? Make sure there is no X11 or wayland server running when you run the command. drm-framebuffer needs to be able to takeover the master role that's why no other application should use the display controller.

**Comment by MirS0bhan** [comment]
hmmm, i think that's the main problem i want it to be run over wayland, in fact i need to be able add some pixels directly to the screen and i thought this source could be do that. what can i do ?

**Comment by eichenberger** [comment]
Unfortunately, this is not possible with this application. It is meant to run without any compositor. You would have to write a normal application that requests memory through wayland. However, then depending on what compositor (e.g. weston) you are using, you won't be able to tell at which location it should put your window.

**Comment by MirS0bhan** [comment]
that's problem. thank you.
